<script setup lang="ts">
import { computed } from 'vue'
const props=defineProps<{page:number;totalPages:number;totalResults?:number;label?:string}>()
const emit=defineEmits<{change:[page:number]}>()
const pages=computed(() => {const total=Math.max(1,props.totalPages);const current=Math.max(1,Math.min(total,props.page));const values:(number|string)[]=[];const start=Math.max(1,current-2),end=Math.min(total,current+2);if(start>1){values.push(1);if(start>2)values.push('start-gap')}for(let value=start;value<=end;value+=1)values.push(value);if(end<total){if(end<total-1)values.push('end-gap');values.push(total)}return values})
function change(value:number){if(value!==props.page&&value>=1&&value<=props.totalPages)emit('change',value)}
</script>
<template><div v-if="totalPages>1" class="pagination-shell"><nav class="pagination-nav" aria-label="分页导航"><button class="pagination-side" :disabled="page<=1" @click="change(page-1)"><span class="material-symbols-outlined text-lg">chevron_left</span><span class="hidden sm:inline">上一页</span></button><template v-for="value in pages" :key="value"><span v-if="typeof value==='string'" class="pagination-gap">…</span><button v-else class="pagination-page" :class="value===page?'is-active':''" :aria-current="value===page?'page':undefined" @click="change(value)">{{value}}</button></template><button class="pagination-side" :disabled="page>=totalPages" @click="change(page+1)"><span class="hidden sm:inline">下一页</span><span class="material-symbols-outlined text-lg">chevron_right</span></button></nav><p v-if="totalResults!=null" class="text-xs text-on-surface-variant">第 {{page}} / {{totalPages}} 页 · 共 {{totalResults.toLocaleString('zh-CN')}} {{label||'条结果'}}</p></div></template>
<style scoped>
.pagination-shell{margin-top:48px;display:flex;flex-direction:column;align-items:center;gap:16px}.pagination-nav{display:flex;align-items:center;gap:6px;border:1px solid rgba(255,255,255,.07);border-radius:14px;background:rgba(29,32,37,.75);padding:7px;box-shadow:0 18px 45px rgba(0,0,0,.18)}.pagination-side,.pagination-page{display:inline-flex;height:42px;align-items:center;justify-content:center;border-radius:9px;font-size:14px;font-weight:700;transition:all .18s ease}.pagination-side{gap:3px;padding:0 14px;color:#e2e2e8}.pagination-page{min-width:42px;padding:0 10px;color:#c5c7ce}.pagination-side:hover:not(:disabled),.pagination-page:hover:not(.is-active){background:#282a30;color:#f5c518;transform:translateY(-1px)}.pagination-page.is-active{background:#f5c518;color:#111;box-shadow:0 7px 18px rgba(245,197,24,.18)}.pagination-side:disabled{pointer-events:none;opacity:.3}.pagination-gap{display:flex;height:42px;min-width:28px;align-items:center;justify-content:center;color:#777b84}@media(max-width:520px){.pagination-nav{gap:3px;padding:5px}.pagination-page{min-width:36px;height:38px}.pagination-side{height:38px;padding:0 9px}.pagination-gap{min-width:18px}}
</style>
