
export interface SessionUser { id:number;username:string;email:string;role:'user'|'admin';status:'active'|'suspended';displayName:string;bio:string;avatarUrl:string;bannerUrl:string;profileVisibility:'public'|'private';createdAt:string;lastLoginAt:string|null }
export interface MediaEntry { id:number;userId:number;mediaType:'movie'|'tv';tmdbId:number;imdbId:string|null;title:string;posterUrl:string|null;releaseYear:number|null;watchStatus:'want'|'watching'|'watched'|null;favorite:boolean;rating:number|null;reviewText:string|null;containsSpoiler:boolean;reviewStatus:'published'|'hidden';watchedAt:string|null;createdAt:string;updatedAt:string;user?:{username:string;displayName:string;avatarUrl?:string} }
export interface ProfileData { user:SessionUser;stats:Record<string,number>;entries:MediaEntry[];history?:{browse:Array<Record<string,unknown>>;search:Array<Record<string,unknown>>} }
interface ApiEnvelope<T>{data:T|null;error:{code:string;message:string}|null}
export async function userRequest<T>(path:string,options:RequestInit={}){const response=await fetch(path,{...options,credentials:'include',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});const text=await response.text();let body:ApiEnvelope<T>;try{body=JSON.parse(text)}catch{throw new Error('服务器返回的数据格式无效')}if(!response.ok||body.data==null)throw new Error(body.error?.message||'请求失败');return body.data}
export const authApi={me:()=>userRequest<{user:SessionUser|null}>('/api/v1/auth/me'),login:(identifier:string,password:string)=>userRequest<{user:SessionUser}>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({identifier,password})}),register:(input:{username:string;email:string;password:string;displayName:string})=>userRequest<{user:SessionUser}>('/api/v1/auth/register',{method:'POST',body:JSON.stringify(input)}),logout:()=>userRequest<{loggedOut:boolean}>('/api/v1/auth/logout',{method:'POST'})}
export const profileApi={own:()=>userRequest<ProfileData>('/api/v1/me/profile'),public:(username:string)=>userRequest<ProfileData>(`/api/v1/users/${encodeURIComponent(username)}`),update:(input:Record<string,unknown>)=>userRequest<{user:SessionUser}>('/api/v1/me/profile',{method:'PUT',body:JSON.stringify(input)}),password:(currentPassword:string,nextPassword:string)=>userRequest('/api/v1/me/password',{method:'PUT',body:JSON.stringify({currentPassword,nextPassword})}),history:()=>userRequest<{browse:Array<Record<string,unknown>>;search:Array<Record<string,unknown>>}>('/api/v1/me/history'),clearHistory:(type:'browse'|'search')=>userRequest(`/api/v1/me/history/${type}`,{method:'DELETE'})}
export const mediaApi={get:(type:string,id:number)=>userRequest<MediaEntry|null>(`/api/v1/me/media/${type}/${id}`),remove:(type:string,id:number)=>userRequest(`/api/v1/me/media/${type}/${id}`,{method:'DELETE'}),save:(type:string,id:number,input:Record<string,unknown>)=>userRequest<MediaEntry>(`/api/v1/me/media/${type}/${id}`,{method:'PUT',body:JSON.stringify(input)}),reviews:(type:string,id:number)=>userRequest<MediaEntry[]>(`/api/v1/titles/${type}/${id}/reviews`)}
export const adminApi={overview:()=>userRequest<Record<string,any>>('/api/v1/admin/overview'),users:(query='')=>userRequest<Record<string,any>>(`/api/v1/admin/users?query=${encodeURIComponent(query)}`),updateUser:(id:number,input:Record<string,unknown>)=>userRequest<SessionUser>(`/api/v1/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(input)}),reviews:(status='')=>userRequest<MediaEntry[]>(`/api/v1/admin/reviews?status=${status}`),moderate:(id:number,status:string)=>userRequest(`/api/v1/admin/reviews/${id}`,{method:'PATCH',body:JSON.stringify({status})}),logs:()=>userRequest<Record<string,any>>('/api/v1/admin/logs')}
