
import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto'
import { promisify } from 'node:util'
import { getDatabase } from './database.mjs'

const scrypt = promisify(scryptCallback)
export const sessionDays = Math.max(1, Number(process.env.SESSION_DAYS || 30))
const defaultAvatar = 'https://placehold.co/400x400/24262b/f5c518?text=MS'
const defaultBanner = 'https://placehold.co/1600x500/17191d/e2e2e8?text=MovieScope'

export function httpError(status, message, code = 'REQUEST_FAILED') { const error = new Error(message); error.status = status; error.code = code; return error }
function text(value, max = 255) { return String(value || '').trim().slice(0, max) }
function nullable(value, max = 500) { const result = text(value, max); return result || null }
function hashToken(token) { return createHash('sha256').update(token).digest('hex') }
function publicUser(row) { return { id: Number(row.id), username: row.username, email: row.email, role: row.role, status: row.status, displayName: row.display_name, bio: row.bio || '', avatarUrl: row.avatar_url || defaultAvatar, bannerUrl: row.banner_url || defaultBanner, profileVisibility: row.profile_visibility, createdAt: row.created_at, lastLoginAt: row.last_login_at } }
function publicProfileUser(row) { const user = publicUser(row); delete user.email; delete user.status; delete user.lastLoginAt; return user }

export async function hashPassword(password) {
  if (typeof password !== 'string' || password.length < 8 || password.length > 128) throw httpError(400, '密码长度必须为 8 到 128 位', 'INVALID_PASSWORD')
  const salt = randomBytes(16), derived = await scrypt(password, salt, 64)
  return `scrypt$${salt.toString('hex')}$${Buffer.from(derived).toString('hex')}`
}
export async function verifyPassword(password, stored) {
  const [algorithm, saltHex, hashHex] = String(stored || '').split('$')
  if (algorithm !== 'scrypt' || !saltHex || !hashHex) return false
  const expected = Buffer.from(hashHex, 'hex'), actual = Buffer.from(await scrypt(password, Buffer.from(saltHex, 'hex'), expected.length))
  return actual.length === expected.length && timingSafeEqual(actual, expected)
}
export async function registerUser(input) {
  const username = text(input.username, 32), email = text(input.email, 190).toLowerCase(), displayName = text(input.displayName || username, 60)
  if (!/^[\p{L}\p{N}_-]{3,32}$/u.test(username)) throw httpError(400, '用户名需为 3 到 32 位文字、数字、下划线或短横线', 'INVALID_USERNAME')
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw httpError(400, '请输入有效邮箱地址', 'INVALID_EMAIL')
  if (!displayName) throw httpError(400, '显示名称不能为空', 'INVALID_DISPLAY_NAME')
  const passwordHash = await hashPassword(input.password), db = await getDatabase()
  try { const result = await db.query('INSERT INTO users (username,email,password_hash,display_name) VALUES (?,?,?,?)', [username,email,passwordHash,displayName]); return getUserById(result.result.insertId) }
  catch (error) { if (error?.code === 'ER_DUP_ENTRY') throw httpError(409, '用户名或邮箱已被注册', 'ACCOUNT_EXISTS'); throw error }
}
async function loginAttemptKey(identifier){return createHash('sha256').update(identifier).digest('hex')}
export async function authenticateUser(identifierValue, password, ipAddress='') {
  const identifier = text(identifierValue,190).toLowerCase(), db = await getDatabase(), ip=text(ipAddress,64)||'unknown', identifierHash=await loginAttemptKey(identifier)
  const recent=await db.query("SELECT COUNT(*) count FROM auth_login_attempts WHERE identifier_hash=? AND ip_address=? AND success=FALSE AND attempted_at>UTC_TIMESTAMP(3)-INTERVAL 15 MINUTE",[identifierHash,ip])
  if(Number(recent.rows[0]?.count||0)>=8)throw httpError(429,'登录失败次数过多，请 15 分钟后再试','LOGIN_RATE_LIMITED')
  const result = await db.query('SELECT * FROM users WHERE LOWER(email)=? OR LOWER(username)=? LIMIT 1',[identifier,identifier]), row=result.rows[0]
  if (!row || !(await verifyPassword(password,row.password_hash))){await db.query('INSERT INTO auth_login_attempts (identifier_hash,ip_address,success) VALUES (?,?,FALSE)',[identifierHash,ip]);throw httpError(401,'账号或密码错误','INVALID_CREDENTIALS')}
  if (row.status !== 'active') throw httpError(403,'账号已被停用，请联系管理员','ACCOUNT_SUSPENDED')
  await db.query('INSERT INTO auth_login_attempts (identifier_hash,ip_address,success) VALUES (?,?,TRUE)',[identifierHash,ip]);await db.query('DELETE FROM auth_login_attempts WHERE attempted_at<UTC_TIMESTAMP(3)-INTERVAL 1 DAY');await db.query('UPDATE users SET last_login_at=UTC_TIMESTAMP(3) WHERE id=?',[row.id]); return publicUser({...row,last_login_at:new Date()})
}
export async function getUserById(id) { const db=await getDatabase(), result=await db.query('SELECT * FROM users WHERE id=? LIMIT 1',[id]); if(!result.rows[0])throw httpError(404,'用户不存在','USER_NOT_FOUND'); return publicUser(result.rows[0]) }
export async function createSession(userId,meta={}) { const token=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+sessionDays*86400000),db=await getDatabase();await db.query('INSERT INTO user_sessions (user_id,token_hash,ip_address,user_agent,expires_at) VALUES (?,?,?,?,?)',[userId,hashToken(token),nullable(meta.ip,64),nullable(meta.userAgent,500),expiresAt]);return{token,expiresAt} }
export async function getSessionUser(token) { if(!token)return null;const db=await getDatabase(),result=await db.query('SELECT u.*,s.id session_id FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>UTC_TIMESTAMP(3) LIMIT 1',[hashToken(token)]),row=result.rows[0];if(!row||row.status!=='active')return null;await db.query('UPDATE user_sessions SET last_seen_at=UTC_TIMESTAMP(3) WHERE id=?',[row.session_id]);return publicUser(row) }
export async function revokeSession(token){if(!token)return;const db=await getDatabase();await db.query('UPDATE user_sessions SET revoked_at=UTC_TIMESTAMP(3) WHERE token_hash=?',[hashToken(token)])}
export async function updateProfile(userId,input){const displayName=text(input.displayName,60),bio=text(input.bio,500),visibility=input.profileVisibility==='private'?'private':'public';if(!displayName)throw httpError(400,'显示名称不能为空');const db=await getDatabase();await db.query('UPDATE users SET display_name=?,bio=?,avatar_url=?,banner_url=?,profile_visibility=? WHERE id=?',[displayName,bio,nullable(input.avatarUrl,500),nullable(input.bannerUrl,500),visibility,userId]);return getUserById(userId)}
export async function changePassword(userId,currentPassword,nextPassword){const db=await getDatabase(),result=await db.query('SELECT password_hash FROM users WHERE id=?',[userId]),row=result.rows[0];if(!row||!(await verifyPassword(currentPassword,row.password_hash)))throw httpError(400,'当前密码不正确','INVALID_CURRENT_PASSWORD');const passwordHash=await hashPassword(nextPassword);await db.query('UPDATE users SET password_hash=? WHERE id=?',[passwordHash,userId]);await db.query('UPDATE user_sessions SET revoked_at=UTC_TIMESTAMP(3) WHERE user_id=?',[userId])}

function mediaEntry(row){return{id:Number(row.id),userId:Number(row.user_id),mediaType:row.media_type,tmdbId:Number(row.tmdb_id),imdbId:row.imdb_id,title:row.title,posterUrl:row.poster_url,releaseYear:row.release_year?Number(row.release_year):null,watchStatus:row.watch_status,favorite:Boolean(row.is_favorite),rating:row.rating==null?null:Number(row.rating),reviewText:row.review_text,containsSpoiler:Boolean(row.contains_spoiler),reviewStatus:row.review_status,watchedAt:row.watched_at,createdAt:row.created_at,updatedAt:row.updated_at}}
export async function upsertMediaEntry(userId,input){const mediaType=input.mediaType==='tv'?'tv':input.mediaType==='movie'?'movie':null,tmdbId=Number(input.tmdbId),watchStatus=['want','watching','watched'].includes(input.watchStatus)?input.watchStatus:null,rating=input.rating===null||input.rating===''||input.rating===undefined?null:Number(input.rating),reviewText=nullable(input.reviewText,5000);if(!mediaType||!Number.isInteger(tmdbId)||tmdbId<1)throw httpError(400,'影视条目标识无效');if(!text(input.title,255))throw httpError(400,'影视标题不能为空');if(rating!=null&&(!Number.isFinite(rating)||rating<.5||rating>10))throw httpError(400,'评分必须在 0.5 到 10 之间');const watchedAt=watchStatus==='watched'?new Date():null,db=await getDatabase();await db.query(`INSERT INTO user_media_entries (user_id,media_type,tmdb_id,imdb_id,title,poster_url,release_year,watch_status,is_favorite,rating,review_text,contains_spoiler,watched_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE imdb_id=VALUES(imdb_id),title=VALUES(title),poster_url=VALUES(poster_url),release_year=VALUES(release_year),watch_status=VALUES(watch_status),is_favorite=VALUES(is_favorite),rating=VALUES(rating),review_text=VALUES(review_text),contains_spoiler=VALUES(contains_spoiler),review_status=IF(VALUES(review_text) IS NULL,review_status,'published'),watched_at=COALESCE(VALUES(watched_at),watched_at)`,[userId,mediaType,tmdbId,nullable(input.imdbId,20),text(input.title,255),nullable(input.posterUrl,500),Number(input.releaseYear)||null,watchStatus,Boolean(input.favorite),rating,reviewText,Boolean(input.containsSpoiler),watchedAt]);return getMediaEntry(userId,mediaType,tmdbId)}
export async function getMediaEntry(userId,mediaType,tmdbId){const db=await getDatabase(),result=await db.query('SELECT * FROM user_media_entries WHERE user_id=? AND media_type=? AND tmdb_id=? LIMIT 1',[userId,mediaType,tmdbId]);return result.rows[0]?mediaEntry(result.rows[0]):null}
export async function deleteMediaEntry(userId,mediaType,tmdbId){const db=await getDatabase();await db.query('DELETE FROM user_media_entries WHERE user_id=? AND media_type=? AND tmdb_id=?',[userId,mediaType,tmdbId])}
export async function listMediaEntries(userId,params={}){const filters=['user_id=?'],values=[userId];if(['want','watching','watched'].includes(params.status)){filters.push('watch_status=?');values.push(params.status)}if(params.favorite==='true')filters.push('is_favorite=TRUE');if(params.reviewed==='true')filters.push("review_text IS NOT NULL AND review_text<>''");const db=await getDatabase(),result=await db.query(`SELECT * FROM user_media_entries WHERE ${filters.join(' AND ')} ORDER BY updated_at DESC LIMIT 200`,values);return result.rows.map(mediaEntry)}
export async function recordBrowse(userId,input){if(!userId)return;const mediaType=['movie','tv','person'].includes(input.mediaType)?input.mediaType:null;if(!mediaType||!text(input.sourceId,32)||!text(input.title,255))return;const db=await getDatabase();await db.query('INSERT INTO user_browse_history (user_id,media_type,source_id,title,image_url) VALUES (?,?,?,?,?)',[userId,mediaType,text(input.sourceId,32),text(input.title,255),nullable(input.imageUrl,500)]);await db.query('DELETE FROM user_browse_history WHERE user_id=? AND id NOT IN (SELECT id FROM (SELECT id FROM user_browse_history WHERE user_id=? ORDER BY viewed_at DESC LIMIT 200) recent)',[userId,userId])}
export async function recordSearch(userId,input){if(!userId||!text(input.query,255))return;const db=await getDatabase();await db.query('INSERT INTO user_search_history (user_id,query_text,search_type) VALUES (?,?,?)',[userId,text(input.query,255),text(input.type||'multi',20)])}
export async function getHistory(userId){const db=await getDatabase(),browse=await db.query('SELECT id,media_type mediaType,source_id sourceId,title,image_url imageUrl,viewed_at viewedAt FROM user_browse_history WHERE user_id=? ORDER BY viewed_at DESC LIMIT 100',[userId]),search=await db.query('SELECT id,query_text queryText,search_type searchType,searched_at searchedAt FROM user_search_history WHERE user_id=? ORDER BY searched_at DESC LIMIT 100',[userId]);return{browse:browse.rows,search:search.rows}}
export async function clearHistory(userId,type){const db=await getDatabase();if(type==='browse')await db.query('DELETE FROM user_browse_history WHERE user_id=?',[userId]);else if(type==='search')await db.query('DELETE FROM user_search_history WHERE user_id=?',[userId]);else throw httpError(400,'历史类型无效')}
async function profileStats(userId){const db=await getDatabase(),result=await db.query(`SELECT COUNT(*) total,SUM(watch_status='want') wantCount,SUM(watch_status='watching') watchingCount,SUM(watch_status='watched') watchedCount,SUM(is_favorite=TRUE) favoriteCount,SUM(rating IS NOT NULL) ratingCount,SUM(review_text IS NOT NULL AND review_text<>'') reviewCount,ROUND(AVG(rating),1) averageRating FROM user_media_entries WHERE user_id=?`,[userId]),row=result.rows[0]||{};return Object.fromEntries(Object.entries(row).map(([key,value])=>[key,value==null?0:Number(value)]))}
export async function getOwnProfile(userId){const user=await getUserById(userId),stats=await profileStats(userId),entries=await listMediaEntries(userId),history=await getHistory(userId);return{user,stats,entries,history}}
export async function getPublicProfile(username,viewerId=null){const db=await getDatabase(),result=await db.query("SELECT * FROM users WHERE username=? AND status='active' LIMIT 1",[username]),row=result.rows[0];if(!row)throw httpError(404,'用户不存在');if(row.profile_visibility==='private'&&Number(row.id)!==Number(viewerId))throw httpError(403,'该用户的主页未公开');const stats=await profileStats(row.id),entries=await db.query("SELECT * FROM user_media_entries WHERE user_id=? AND (watch_status IS NOT NULL OR rating IS NOT NULL OR review_text IS NOT NULL) AND review_status='published' ORDER BY updated_at DESC LIMIT 80",[row.id]);return{user:publicProfileUser(row),stats,entries:entries.rows.map(mediaEntry)}}
export async function getCommunityReviews(mediaType,tmdbId){const db=await getDatabase(),result=await db.query(`SELECT e.*,u.username,u.display_name,u.avatar_url FROM user_media_entries e JOIN users u ON u.id=e.user_id WHERE e.media_type=? AND e.tmdb_id=? AND e.review_text IS NOT NULL AND e.review_text<>'' AND e.review_status='published' AND u.status='active' AND u.profile_visibility='public' ORDER BY e.updated_at DESC LIMIT 50`,[mediaType,tmdbId]);return result.rows.map(row=>({...mediaEntry(row),user:{username:row.username,displayName:row.display_name,avatarUrl:row.avatar_url||defaultAvatar}}))}

async function audit(admin,action,targetType,targetId,detail,ip){const db=await getDatabase();await db.query('INSERT INTO admin_audit_logs (admin_user_id,action,target_type,target_id,detail,ip_address) VALUES (?,?,?,?,?,?)',[admin.id,action,targetType,targetId||null,detail?JSON.stringify(detail):null,nullable(ip,64)])}
export async function getAdminOverview(){const db=await getDatabase(),users=await db.query("SELECT COUNT(*) count,SUM(role='admin') admins,SUM(status='suspended') suspended FROM users"),entries=await db.query("SELECT COUNT(*) count,SUM(watch_status='watched') watched,SUM(rating IS NOT NULL) ratings FROM user_media_entries"),reviews=await db.query("SELECT COUNT(*) count,SUM(review_status='hidden') hidden FROM user_media_entries WHERE review_text IS NOT NULL"),sessions=await db.query('SELECT COUNT(*) count FROM user_sessions WHERE revoked_at IS NULL AND expires_at>UTC_TIMESTAMP(3)'),cache=await db.query('SELECT provider,COUNT(*) count,SUM(expires_at>UTC_TIMESTAMP()) active FROM api_cache GROUP BY provider'),errors=await db.query("SELECT COUNT(*) count FROM provider_sync_logs WHERE status='error' AND created_at>UTC_TIMESTAMP()-INTERVAL 24 HOUR");return{users:users.rows[0],entries:entries.rows[0],reviews:reviews.rows[0],activeSessions:Number(sessions.rows[0]?.count||0),cache:cache.rows,providerErrors24h:Number(errors.rows[0]?.count||0)}}
export async function adminListUsers(params={}){const page=Math.max(1,Number(params.page)||1),size=30,query=text(params.query,100),where=query?'WHERE username LIKE ? OR email LIKE ? OR display_name LIKE ?':'',values=query?['%'+query+'%','%'+query+'%','%'+query+'%']:[],db=await getDatabase(),list=await db.query(`SELECT id,username,email,role,status,display_name,bio,avatar_url,profile_visibility,last_login_at,created_at FROM users ${where} ORDER BY created_at DESC LIMIT ? OFFSET ?`,[...values,size,(page-1)*size]),total=await db.query(`SELECT COUNT(*) count FROM users ${where}`,values);return{page,totalPages:Math.ceil(Number(total.rows[0].count)/size),totalResults:Number(total.rows[0].count),results:list.rows.map(publicUser)}}
export async function adminUpdateUser(admin,userId,input,ip){if(Number(admin.id)===Number(userId)&&(input.status==='suspended'||input.role==='user'))throw httpError(400,'不能停用当前管理员账号或移除自己的管理员权限');const updates=[],values=[];if(['active','suspended'].includes(input.status)){updates.push('status=?');values.push(input.status)}if(['user','admin'].includes(input.role)){updates.push('role=?');values.push(input.role)}if(!updates.length)throw httpError(400,'没有可更新的用户字段');values.push(userId);const db=await getDatabase();await db.query(`UPDATE users SET ${updates.join(',')} WHERE id=?`,values);await audit(admin,'update_user','user',String(userId),input,ip);return getUserById(userId)}
export async function adminListReviews(params={}){const db=await getDatabase(),status=params.status==='hidden'?'hidden':params.status==='published'?'published':null,result=await db.query(`SELECT e.*,u.username,u.display_name FROM user_media_entries e JOIN users u ON u.id=e.user_id WHERE e.review_text IS NOT NULL AND e.review_text<>'' ${status?'AND e.review_status=?':''} ORDER BY e.updated_at DESC LIMIT 200`,status?[status]:[]);return result.rows.map(row=>({...mediaEntry(row),user:{username:row.username,displayName:row.display_name}}))}
export async function adminModerateReview(admin,entryId,status,ip){if(!['published','hidden'].includes(status))throw httpError(400,'审核状态无效');const db=await getDatabase();await db.query('UPDATE user_media_entries SET review_status=? WHERE id=?',[status,entryId]);await audit(admin,'moderate_review','media_entry',String(entryId),{status},ip)}
export async function adminLogs(){const db=await getDatabase(),auditLogs=await db.query('SELECT l.*,u.username adminUsername FROM admin_audit_logs l JOIN users u ON u.id=l.admin_user_id ORDER BY l.created_at DESC LIMIT 100'),syncLogs=await db.query('SELECT id,provider,operation,cache_key cacheKey,status,duration_ms durationMs,error_message errorMessage,created_at createdAt FROM provider_sync_logs ORDER BY created_at DESC LIMIT 100');return{audit:auditLogs.rows,sync:syncLogs.rows}}
export async function promoteUser(identifierValue){const identifier=text(identifierValue,190).toLowerCase(),db=await getDatabase(),result=await db.query("UPDATE users SET role='admin',status='active' WHERE LOWER(username)=? OR LOWER(email)=?",[identifier,identifier]);if(!result.result.affectedRows)throw httpError(404,'用户不存在');return true}
