
<script setup lang="ts">
import {computed,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import {useAuth} from '../composables/useAuth'
const route=useRoute(),router=useRouter(),auth=useAuth(),mode=computed(()=>route.query.mode==='register'?'register':'login'),loading=ref(false),error=ref(''),form=ref({identifier:'',username:'',email:'',displayName:'',password:''})
async function submit(){loading.value=true;error.value='';try{if(mode.value==='login')await auth.login(form.value.identifier,form.value.password);else await auth.register(form.value);router.replace(typeof route.query.redirect==='string'?route.query.redirect:'/me')}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{loading.value=false}}
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto flex min-h-[calc(100vh-50px)] max-w-[1100px] items-center px-4 py-24 md:px-8"><div class="grid w-full overflow-hidden rounded-2xl border border-white/5 bg-surface-container shadow-2xl md:grid-cols-[1.1fr_.9fr]"><section class="relative hidden min-h-[620px] overflow-hidden md:block"><img class="absolute inset-0 h-full w-full object-cover opacity-55" src="https://image.tmdb.org/t/p/original/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg"><div class="absolute inset-0 bg-gradient-to-r from-transparent to-surface-container"></div><div class="absolute bottom-12 left-10 max-w-sm"><p class="text-xs font-bold tracking-[.2em] text-primary">MOVIESCOPE</p><h1 class="mt-3 text-4xl font-extrabold">记录每一次观影，留下属于你的电影时间线。</h1></div></section><section class="p-7 md:p-10"><h1 class="text-3xl font-extrabold">{{mode==='login'?'欢迎回来':'创建账号'}}</h1><p class="mt-2 text-sm text-on-surface-variant">{{mode==='login'?'登录后继续管理观影记录。':'注册后可保存状态、评分、短评与历史。'}}</p><form class="mt-8 space-y-5" @submit.prevent="submit"><label v-if="mode==='login'" class="form-label">用户名或邮箱<input v-model="form.identifier" class="form-input" required autocomplete="username"></label><template v-else><label class="form-label">用户名<input v-model="form.username" class="form-input" required minlength="3" maxlength="32"></label><label class="form-label">显示名称<input v-model="form.displayName" class="form-input" required maxlength="60"></label><label class="form-label">邮箱<input v-model="form.email" class="form-input" required type="email"></label></template><label class="form-label">密码<input v-model="form.password" class="form-input" required minlength="8" type="password" autocomplete="current-password"></label><p v-if="error" class="rounded-lg border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{{error}}</p><button class="h-12 w-full rounded-lg bg-primary-container font-bold text-on-primary-container transition-all hover:brightness-105 disabled:opacity-50" :disabled="loading">{{loading?'处理中…':mode==='login'?'登录':'注册'}}</button></form><RouterLink class="mt-6 block text-center text-sm font-bold text-primary hover:underline" :to="{name:'auth',query:{mode:mode==='login'?'register':'login'}}">{{mode==='login'?'没有账号？立即注册':'已有账号？返回登录'}}</RouterLink></section></div></main><GlobalFooter/></div></template>
<style scoped>.form-label{display:block;font-size:13px;font-weight:700;color:#c5c7ce}.form-input{margin-top:8px;width:100%;border:1px solid rgba(255,255,255,.1);border-radius:8px;background:#282a30;padding:12px;color:#e2e2e8;outline:none}.form-input:focus{border-color:rgba(245,197,24,.6)}</style>
