<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import CatalogPosterCard from '../components/catalog/CatalogPosterCard.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchDiscover } from '../services/catalog-api'
const route=useRoute(),router=useRouter()
const form=reactive({media:route.query.media==='tv'?'tv':'movie',genres:String(route.query.genres||''),year:String(route.query.year||''),rating:Number(route.query.rating||0),language:String(route.query.language||''),sort:String(route.query.sort||'popularity.desc')})
const page=computed(()=>Number(route.query.page||1)),key=computed(()=>JSON.stringify(route.query))
const {data,loading,error,reload}=useAsyncData(()=>fetchDiscover({media:form.media,genres:form.genres||undefined,year:form.year||undefined,rating:form.rating||undefined,language:form.language||undefined,sort:form.sort,page:page.value}),[key])
const genres=computed(()=>data.value?.genres[form.media as 'movie'|'tv']||[])
const years=[2026,2025,2024,2023,2022,2021,2020,2019,2018]
const languages=[{value:'',label:'全部'},{value:'zh',label:'中文'},{value:'en',label:'英语'},{value:'ja',label:'日语'},{value:'ko',label:'韩语'},{value:'fr',label:'法语'}]
const ratings=[{value:0,label:'全部'},{value:6,label:'6.0+'},{value:7,label:'7.0+'},{value:8,label:'8.0+'}]
const sorts=computed(()=>[{value:'popularity.desc',label:'热门'},{value:'vote_average.desc',label:'评分最高'},{value:form.media==='tv'?'first_air_date.desc':'primary_release_date.desc',label:'最新发行'},...(form.media==='movie'?[{value:'revenue.desc',label:'票房最高'}]:[])])
function sync(){router.push({name:'explore',query:{media:form.media,genres:form.genres||undefined,year:form.year||undefined,rating:form.rating||undefined,language:form.language||undefined,sort:form.sort,page:1}})}
function choose(field:'media'|'genres'|'year'|'rating'|'language',value:string|number){if(field==='media'){form.media=String(value);form.genres='';form.sort='popularity.desc'}else if(field==='rating')form.rating=Number(value);else form[field]=String(value);sync()}
function setPage(value:number){router.push({query:{...route.query,page:Math.max(1,Math.min(data.value?.totalPages||1,value))}});scrollTo({top:0,behavior:'smooth'})}
watch(()=>route.query,()=>{form.media=route.query.media==='tv'?'tv':'movie';form.genres=String(route.query.genres||'');form.year=String(route.query.year||'');form.rating=Number(route.query.rating||0);form.language=String(route.query.language||'');form.sort=String(route.query.sort||'popularity.desc')},{deep:true})
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/>
<div class="mx-auto min-h-screen max-w-[1216px] px-4 pb-16 pt-[82px] md:px-8"><div class="mt-6 flex flex-col gap-10 lg:flex-row">
<main class="min-w-0 flex-1">
  <section class="mb-8 space-y-2 rounded-lg border border-white/10 bg-surface-container-low/30 p-4 text-[13px]">
    <div class="filter-row"><span class="filter-label">内容：</span><div class="filter-values"><button :class="form.media==='movie'?'active-filter':'filter-option'" @click="choose('media','movie')">电影</button><button :class="form.media==='tv'?'active-filter':'filter-option'" @click="choose('media','tv')">剧集</button></div></div>
    <div class="filter-row"><span class="filter-label">类型：</span><div class="filter-values"><button :class="!form.genres?'active-filter':'filter-option'" @click="choose('genres','')">全部</button><button v-for="genre in genres" :key="genre.id" :class="form.genres===String(genre.id)?'active-filter':'filter-option'" @click="choose('genres',genre.id)">{{genre.name}}</button></div></div>
    <div class="filter-row"><span class="filter-label">年代：</span><div class="filter-values"><button :class="!form.year?'active-filter':'filter-option'" @click="choose('year','')">全部</button><button v-for="year in years" :key="year" :class="form.year===String(year)?'active-filter':'filter-option'" @click="choose('year',year)">{{year}}</button></div></div>
    <div class="filter-row"><span class="filter-label">语言：</span><div class="filter-values"><button v-for="language in languages" :key="language.value" :class="form.language===language.value?'active-filter':'filter-option'" @click="choose('language',language.value)">{{language.label}}</button></div></div>
    <div class="filter-row"><span class="filter-label">评分：</span><div class="filter-values"><button v-for="rating in ratings" :key="rating.value" :class="form.rating===rating.value?'active-filter':'filter-option'" @click="choose('rating',rating.value)">{{rating.label}}</button></div></div>
  </section>
  <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-3xl font-bold">探索影界</h1><p class="mt-1 text-sm text-on-surface-variant">共发现 <strong class="text-on-surface">{{data?.totalResults.toLocaleString('zh-CN')||0}}</strong> 部符合条件的内容</p></div><label class="group flex items-center gap-2"><span class="text-sm font-bold text-on-surface-variant transition-colors group-hover:text-primary">排序：</span><select v-model="form.sort" class="rounded-lg border border-white/10 bg-surface-container-high/50 px-3 py-1.5 text-sm font-bold transition-colors hover:border-primary/50" @change="sync"><option v-for="sort in sorts" :key="sort.value" :value="sort.value">{{sort.label}}</option></select></label></div>
  <PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><div class="grid grid-cols-2 gap-6 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5"><CatalogPosterCard v-for="item in data.results" :key="item.id" :item="item"/></div><div v-if="data.totalPages>1" class="mb-20 mt-20 flex flex-col items-center gap-6"><nav class="flex items-center gap-2"><button class="page-button" :disabled="page<=1" @click="setPage(page-1)"><span class="material-symbols-outlined text-sm">chevron_left</span>上一页</button><span class="flex h-10 min-w-10 items-center justify-center rounded bg-primary-container px-3 font-bold text-on-primary-container">{{page}}</span><span class="px-2 text-sm text-on-surface-variant">/ {{data.totalPages}}</span><button class="page-button" :disabled="page>=data.totalPages" @click="setPage(page+1)">下一页<span class="material-symbols-outlined text-sm">chevron_right</span></button></nav><p class="text-xs text-on-surface-variant">当前第 {{page}} 页，共 {{data.totalResults.toLocaleString('zh-CN')}} 部</p></div></template></PageState>
</main>
<aside class="hidden w-80 shrink-0 space-y-12 border-l border-white/10 pl-8 lg:block"><div class="pt-2"><h2 class="mb-8 flex items-center gap-2 text-3xl font-bold"><span class="h-6 w-1 bg-primary"></span>热门榜单</h2><div class="space-y-8"><RouterLink to="/?#高分榜" class="chart-link"><div><h4>IMDb Top 250</h4><span>榜单</span></div><p>影史公认的最佳电影前 250 名</p></RouterLink><RouterLink :to="{name:'explore',query:{media:'movie',sort:'popularity.desc'}}" class="chart-link"><div><h4>近期最受关注</h4><span>热门</span></div><p>当前热度最高的电影作品</p></RouterLink><RouterLink :to="{name:'explore',query:{media:'movie',sort:'revenue.desc'}}" class="chart-link"><div><h4>全球票房</h4><span>票房</span></div><p>按公开票房数据排序的电影</p></RouterLink></div></div></aside>
</div></div><GlobalFooter/></div></template>
<style scoped>
.filter-row{display:flex;align-items:flex-start;gap:16px}.filter-label{width:48px;flex:none;padding-top:4px;color:#c5c7ce}.filter-values{display:flex;flex-wrap:wrap;column-gap:12px;row-gap:4px}.filter-option,.active-filter{cursor:pointer;border-radius:4px;padding:2px 8px;transition:color .18s,background-color .18s}.filter-option:hover{color:#f5c518}.active-filter{background:#f5c518;color:#111;font-weight:700}.page-button{display:flex;height:40px;align-items:center;gap:4px;border:1px solid rgba(255,255,255,.12);border-radius:4px;padding:0 16px;font-size:14px;font-weight:700;transition:all .18s}.page-button:hover:not(:disabled){background:#1d2025;color:#f5c518}.page-button:disabled{pointer-events:none;opacity:.3}.chart-link{display:block;border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:16px}.chart-link:last-child{border:0}.chart-link div{display:flex;align-items:baseline;justify-content:space-between}.chart-link h4{font-weight:700;transition:color .18s}.chart-link:hover h4{color:#f5c518}.chart-link span{font-size:10px;font-weight:700;color:#f5c518}.chart-link p{margin-top:4px;font-size:12px;color:#c5c7ce}
</style>
