<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import CatalogPosterCard from '../components/catalog/CatalogPosterCard.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchDiscover } from '../services/catalog-api'

const route=useRoute();const router=useRouter();const filtersOpen=ref(false)
const form=reactive({media:route.query.media==='tv'?'tv':'movie',genres:typeof route.query.genres==='string'?route.query.genres:'',year:typeof route.query.year==='string'?route.query.year:'',rating:Number(route.query.rating||0),language:typeof route.query.language==='string'?route.query.language:'',provider:typeof route.query.provider==='string'?route.query.provider:'',sort:typeof route.query.sort==='string'?route.query.sort:'popularity.desc'})
const page=computed(()=>Number(route.query.page||1));const key=computed(()=>JSON.stringify(route.query))
function queryValue(value: unknown) { return typeof value === 'string' ? value : undefined }
const {data,loading,error,reload}=useAsyncData(()=>fetchDiscover({media:queryValue(route.query.media)||form.media,genres:queryValue(route.query.genres),year:queryValue(route.query.year),rating:queryValue(route.query.rating),language:queryValue(route.query.language),provider:queryValue(route.query.provider),sort:queryValue(route.query.sort)||form.sort,page:page.value}),[key])
const genres=computed(()=>data.value?.genres[form.media as 'movie' | 'tv']||[])
function apply(){router.push({name:'explore',query:{media:form.media,genres:form.genres||undefined,year:form.year||undefined,rating:form.rating||undefined,language:form.language||undefined,provider:form.provider||undefined,sort:form.sort,page:1}});filtersOpen.value=false}
function reset(){Object.assign(form,{media:'movie',genres:'',year:'',rating:0,language:'',provider:'',sort:'popularity.desc'});apply()}
function setPage(value:number){router.push({query:{...route.query,page:Math.max(1,Math.min(data.value?.totalPages||1,value))}})}
watch(()=>route.query,()=>{form.media=route.query.media==='tv'?'tv':'movie';form.genres=String(route.query.genres||'');form.year=String(route.query.year||'');form.rating=Number(route.query.rating||0);form.language=String(route.query.language||'');form.provider=String(route.query.provider||'');form.sort=String(route.query.sort||'popularity.desc')},{deep:true})
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto max-w-[1216px] px-4 pb-16 pt-[82px] md:px-8">
<header class="mb-7 flex flex-col justify-between gap-5 border-b border-white/10 pb-7 md:flex-row md:items-end"><div><p class="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">发现你的下一部作品</p><h1 class="text-3xl font-extrabold md:text-4xl">探索影界</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-on-surface-variant">按照类型、年份、语言与评分，从真实影视数据库中筛选电影和剧集。</p></div><button class="inline-flex h-10 items-center gap-2 rounded bg-primary-container px-4 text-sm font-bold text-on-primary-container md:hidden" @click="filtersOpen=!filtersOpen"><span class="material-symbols-outlined">tune</span>筛选条件</button></header>
<section :class="filtersOpen?'block':'hidden'" class="mb-8 rounded-xl border border-white/5 bg-surface-container p-5 md:block"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><label class="text-xs font-bold text-on-surface-variant">内容类型<select v-model="form.media" class="mt-2 w-full rounded bg-surface-variant px-3 py-2.5 text-sm text-on-surface"><option value="movie">电影</option><option value="tv">剧集</option></select></label><label class="text-xs font-bold text-on-surface-variant">影视类型<select v-model="form.genres" class="mt-2 w-full rounded bg-surface-variant px-3 py-2.5 text-sm text-on-surface"><option value="">全部类型</option><option v-for="genre in genres" :key="genre.id" :value="genre.id">{{genre.name}}</option></select></label><label class="text-xs font-bold text-on-surface-variant">发行年份<input v-model="form.year" class="mt-2 w-full rounded bg-surface-variant px-3 py-2.5 text-sm text-on-surface" placeholder="例如 2024" inputmode="numeric"></label><label class="text-xs font-bold text-on-surface-variant">最低评分<select v-model.number="form.rating" class="mt-2 w-full rounded bg-surface-variant px-3 py-2.5 text-sm text-on-surface"><option :value="0">不限</option><option :value="6">6.0+</option><option :value="7">7.0+</option><option :value="8">8.0+</option></select></label><label class="text-xs font-bold text-on-surface-variant">原始语言<select v-model="form.language" class="mt-2 w-full rounded bg-surface-variant px-3 py-2.5 text-sm text-on-surface"><option value="">全部语言</option><option value="zh">中文</option><option value="en">英语</option><option value="ja">日语</option><option value="ko">韩语</option><option value="fr">法语</option></select></label><label class="text-xs font-bold text-on-surface-variant">排序方式<select v-model="form.sort" class="mt-2 w-full rounded bg-surface-variant px-3 py-2.5 text-sm text-on-surface"><option value="popularity.desc">热度最高</option><option value="vote_average.desc">评分最高</option><option :value="form.media==='tv'?'first_air_date.desc':'primary_release_date.desc'">最新发行</option><option v-if="form.media==='movie'" value="revenue.desc">票房最高</option></select></label></div><div class="mt-5 flex justify-end gap-2"><button class="rounded px-4 py-2 text-sm font-bold text-on-surface-variant hover:text-on-surface" @click="reset">重置</button><button class="rounded bg-primary-container px-5 py-2 text-sm font-bold text-on-primary-container" @click="apply">应用筛选</button></div></section>
<PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><div class="mb-5 flex items-end justify-between"><div><h2 class="text-2xl font-extrabold">{{data.mediaType==='tv'?'剧集':'电影'}}精选</h2><p class="mt-1 text-sm text-on-surface-variant">共 {{data.totalResults.toLocaleString('zh-CN')}} 部作品</p></div><span class="text-xs font-bold uppercase tracking-widest text-primary">第 {{data.page}} 页</span></div><div class="grid grid-cols-2 gap-x-4 gap-y-7 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6"><CatalogPosterCard v-for="item in data.results" :key="item.id" :item="item"/></div><nav v-if="data.totalPages>1" class="mt-10 flex items-center justify-center gap-2"><button class="h-10 rounded bg-surface-container px-4 disabled:opacity-40" :disabled="page<=1" @click="setPage(page-1)">上一页</button><span class="flex h-10 min-w-10 items-center justify-center rounded bg-primary-container px-3 font-bold text-on-primary-container">{{page}}</span><span class="text-sm text-on-surface-variant">/ {{data.totalPages}}</span><button class="h-10 rounded bg-surface-container px-4 disabled:opacity-40" :disabled="page>=data.totalPages" @click="setPage(page+1)">下一页</button></nav></template></PageState>
<section class="mt-14"><h2 class="mb-5 text-2xl font-extrabold">热门榜单</h2><div class="grid gap-4 md:grid-cols-3"><RouterLink to="/?#高分榜" class="rounded-xl border border-white/5 bg-surface-container p-5 hover:bg-surface-container-high"><p class="text-[10px] font-black tracking-widest text-primary">CHART</p><h3 class="mt-2 text-lg font-bold">IMDb Top 250</h3><p class="mt-2 text-sm text-on-surface-variant">影史公认的最佳电影前 250 名</p></RouterLink><RouterLink :to="{name:'explore',query:{media:'movie',sort:'popularity.desc'}}" class="rounded-xl border border-white/5 bg-surface-container p-5 hover:bg-surface-container-high"><p class="text-[10px] font-black tracking-widest text-primary">POPULAR</p><h3 class="mt-2 text-lg font-bold">近期最受关注</h3><p class="mt-2 text-sm text-on-surface-variant">当前热度最高的电影作品</p></RouterLink><RouterLink :to="{name:'explore',query:{media:'movie',sort:'revenue.desc'}}" class="rounded-xl border border-white/5 bg-surface-container p-5 hover:bg-surface-container-high"><p class="text-[10px] font-black tracking-widest text-primary">BOX OFFICE</p><h3 class="mt-2 text-lg font-bold">全球票房</h3><p class="mt-2 text-sm text-on-surface-variant">按公开票房数据排序的电影</p></RouterLink></div></section>
</main><GlobalFooter/></div></template>
