<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import CatalogPosterGrid from '../components/catalog/CatalogPosterGrid.vue'
import PageState from '../components/catalog/PageState.vue'
import PaginationBar from '../components/catalog/PaginationBar.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchDiscover } from '../services/catalog-api'
const route=useRoute(),router=useRouter()
const form=reactive({media:route.query.media==='tv'?'tv':'movie',genres:String(route.query.genres||''),year:String(route.query.year||''),yearFrom:String(route.query.yearFrom||''),yearTo:String(route.query.yearTo||''),rating:Number(route.query.rating||0),language:String(route.query.language||''),provider:String(route.query.provider||''),watchRegion:String(route.query.watchRegion||''),sort:String(route.query.sort||'popularity.desc')})
const page=computed(()=>Number(route.query.page||1)),key=computed(()=>JSON.stringify(route.query))
const {data,loading,error,reload}=useAsyncData(()=>fetchDiscover({media:form.media,genres:form.genres||undefined,year:form.year||undefined,yearFrom:form.yearFrom||undefined,yearTo:form.yearTo||undefined,rating:form.rating||undefined,language:form.language||undefined,provider:form.provider||undefined,watchRegion:form.watchRegion||undefined,sort:form.sort,page:page.value}),[key])
const genres=computed(()=>data.value?.genres[form.media as 'movie'|'tv']||[])
const currentYear=new Date().getFullYear()
const recentYears=Array.from({length:7},(_,index)=>currentYear-index)
const periods=[{label:'2010年代',from:2010,to:2019},{label:'2000年代',from:2000,to:2009},{label:'1990年代',from:1990,to:1999},{label:'1980年代',from:1980,to:1989},{label:'1970年代',from:1970,to:1979},{label:'更早',from:1900,to:1969}]
const languages=[{value:'',label:'全部'},{value:'zh',label:'中文'},{value:'en',label:'英语'},{value:'ja',label:'日语'},{value:'ko',label:'韩语'},{value:'fr',label:'法语'}]
const ratings=[{value:0,label:'全部'},{value:6,label:'6.0+'},{value:7,label:'7.0+'},{value:8,label:'8.0+'}]
const sorts=computed(()=>[{value:'popularity.desc',label:'热门'},{value:'vote_average.desc',label:'评分最高'},{value:form.media==='tv'?'first_air_date.desc':'primary_release_date.desc',label:'最新发行'},...(form.media==='movie'?[{value:'revenue.desc',label:'票房最高'}]:[])])
function sync(){router.push({name:'explore',query:{media:form.media,genres:form.genres||undefined,year:form.year||undefined,yearFrom:form.yearFrom||undefined,yearTo:form.yearTo||undefined,rating:form.rating||undefined,language:form.language||undefined,provider:form.provider||undefined,watchRegion:form.watchRegion||undefined,sort:form.sort,page:1}})}
function choose(field:'media'|'genres'|'rating'|'language',value:string|number){if(field==='media'){form.media=String(value);form.genres='';form.sort='popularity.desc'}else if(field==='rating')form.rating=Number(value);else form[field]=String(value);sync()}
function choosePeriod(from?:number,to?:number){form.year='';form.yearFrom=from?String(from):'';form.yearTo=to?String(to):'';sync()}
function applyYear(){form.yearFrom='';form.yearTo='';sync()}
function setPage(value:number){router.push({query:{...route.query,page:Math.max(1,Math.min(data.value?.totalPages||1,value))}});scrollTo({top:0,behavior:'smooth'})}
watch(()=>route.query,()=>{form.media=route.query.media==='tv'?'tv':'movie';form.genres=String(route.query.genres||'');form.year=String(route.query.year||'');form.yearFrom=String(route.query.yearFrom||'');form.yearTo=String(route.query.yearTo||'');form.rating=Number(route.query.rating||0);form.language=String(route.query.language||'');form.provider=String(route.query.provider||'');form.watchRegion=String(route.query.watchRegion||'');form.sort=String(route.query.sort||'popularity.desc')},{deep:true})
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/>
<div class="mx-auto min-h-screen max-w-[1680px] px-5 pb-16 pt-[82px] sm:px-7 lg:px-10 xl:px-12"><div class="mt-6 flex flex-col gap-8 xl:flex-row">
<main class="min-w-0 flex-1">
  <section class="mb-8 space-y-2 rounded-lg border border-white/10 bg-surface-container-low/30 p-4 text-[13px]">
    <div class="filter-row"><span class="filter-label">内容：</span><div class="filter-values"><button :class="form.media==='movie'?'active-filter':'filter-option'" @click="choose('media','movie')">电影</button><button :class="form.media==='tv'?'active-filter':'filter-option'" @click="choose('media','tv')">剧集</button></div></div>
    <div class="filter-row"><span class="filter-label">类型：</span><div class="filter-values"><button :class="!form.genres?'active-filter':'filter-option'" @click="choose('genres','')">全部</button><button v-for="genre in genres" :key="genre.id" :class="form.genres===String(genre.id)?'active-filter':'filter-option'" @click="choose('genres',genre.id)">{{genre.name}}</button></div></div>
    <div class="filter-row"><span class="filter-label">年份：</span><div class="filter-values"><button :class="!form.year&&!form.yearFrom?'active-filter':'filter-option'" @click="choosePeriod()">全部</button><button v-for="year in recentYears" :key="year" :class="form.year===String(year)?'active-filter':'filter-option'" @click="form.year=String(year);applyYear()">{{year}}</button><button v-for="period in periods" :key="period.label" :class="form.yearFrom===String(period.from)&&form.yearTo===String(period.to)?'active-filter':'filter-option'" @click="choosePeriod(period.from,period.to)">{{period.label}}</button></div></div>
    <div class="filter-row"><span class="filter-label">语言：</span><div class="filter-values"><button v-for="language in languages" :key="language.value" :class="form.language===language.value?'active-filter':'filter-option'" @click="choose('language',language.value)">{{language.label}}</button></div></div>
    <div class="filter-row"><span class="filter-label">评分：</span><div class="filter-values"><button v-for="rating in ratings" :key="rating.value" :class="form.rating===rating.value?'active-filter':'filter-option'" @click="choose('rating',rating.value)">{{rating.label}}</button></div></div>
  </section>
  <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-3xl font-bold">探索影界</h1><p class="mt-1 text-sm text-on-surface-variant">共发现 <strong class="text-on-surface">{{data?.totalResults.toLocaleString('zh-CN')||0}}</strong> 部符合条件的内容</p></div><label class="group flex items-center gap-2"><span class="text-sm font-bold text-on-surface-variant transition-colors group-hover:text-primary">排序：</span><div class="select-shell"><select v-model="form.sort" class="catalog-select" @change="sync"><option v-for="sort in sorts" :key="sort.value" :value="sort.value">{{sort.label}}</option></select><span class="material-symbols-outlined">expand_more</span></div></label></div>
  <PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><CatalogPosterGrid :items="data.results"/><PaginationBar :page="page" :total-pages="data.totalPages" :total-results="data.totalResults" label="部作品" @change="setPage"/></template></PageState>
</main>
<aside class="hidden w-72 shrink-0 space-y-12 border-l border-white/10 pl-8 xl:block 2xl:w-80"><div class="pt-2"><h2 class="mb-8 flex items-center gap-2 text-3xl font-bold"><span class="h-6 w-1 bg-primary"></span>热门榜单</h2><div class="space-y-8"><RouterLink :to="{name:'browse',params:{preset:'imdb-top-250'}}" class="chart-link"><div><h4>IMDb Top 250</h4><span>榜单</span></div><p>IMDb 用户长期评分形成的经典电影榜单</p></RouterLink><RouterLink :to="{name:'explore',query:{media:'movie',sort:'popularity.desc'}}" class="chart-link"><div><h4>近期最受关注</h4><span>热门</span></div><p>当前热度最高的电影作品</p></RouterLink><RouterLink :to="{name:'explore',query:{media:'movie',sort:'revenue.desc'}}" class="chart-link"><div><h4>电影票房榜</h4><span>票房</span></div><p>按已收录电影的公开累计票房排序</p></RouterLink></div></div></aside>
</div></div><GlobalFooter/></div></template>
<style scoped>
.filter-row{display:flex;align-items:flex-start;gap:16px}.filter-label{width:48px;flex:none;padding-top:4px;color:#c5c7ce}.filter-values{display:flex;flex-wrap:wrap;column-gap:12px;row-gap:6px}.filter-option,.active-filter{cursor:pointer;border-radius:4px;padding:2px 8px;transition:color .18s,background-color .18s}.filter-option:hover{color:#f5c518}.active-filter{background:#f5c518;color:#111;font-weight:700}.year-input-wrap{display:flex;overflow:hidden;border:1px solid rgba(255,255,255,.12);border-radius:5px}.year-input-wrap input{width:82px;background:#292929;padding:3px 7px;outline:none}.year-input-wrap button{border-left:1px solid rgba(255,255,255,.1);padding:3px 8px;font-weight:700;transition:.18s}.year-input-wrap button:hover{background:#f5c518;color:#111}.select-shell{position:relative;min-width:132px}.catalog-select{width:100%;appearance:none;border:1px solid rgba(255,255,255,.12);border-radius:7px;background:#292929;padding:8px 38px 8px 12px;font-size:13px;font-weight:800;color:#fff;outline:none;transition:.2s}.select-shell:hover .catalog-select,.catalog-select:focus{border-color:rgba(245,197,24,.65);background:#303030}.select-shell>.material-symbols-outlined{pointer-events:none;position:absolute;right:10px;top:50%;font-size:19px;color:#f5c518;transform:translateY(-50%);transition:transform .2s}.select-shell:focus-within>.material-symbols-outlined{transform:translateY(-50%) rotate(180deg)}.chart-link{display:block;border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:16px}.chart-link:last-child{border:0}.chart-link div{display:flex;align-items:baseline;justify-content:space-between}.chart-link h4{font-weight:700;transition:color .18s}.chart-link:hover h4{color:#f5c518}.chart-link span{font-size:10px;font-weight:700;color:#f5c518}.chart-link p{margin-top:4px;font-size:12px;color:#c5c7ce}
</style>
