<script setup lang="ts">
import { computed,ref } from 'vue'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchNews } from '../services/catalog-api'
import { formatDate } from '../utils/format'
const query=ref(''),{data,loading,error,reload}=useAsyncData(fetchNews)
const results=computed(()=>{const value=query.value.trim().toLocaleLowerCase();if(!value)return data.value||[];return (data.value||[]).filter(item=>[item.title,item.summary,item.category].some(text=>text.toLocaleLowerCase().includes(value)))})
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto max-w-[1060px] px-4 pb-16 pt-[82px] md:px-8"><header class="mb-8 border-b border-white/10 pb-6"><p class="text-xs font-bold uppercase tracking-widest text-primary">IMDb 新闻</p><div class="mt-2 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 class="text-3xl font-extrabold md:text-4xl">影坛动态</h1></div><label class="relative block w-full md:max-w-sm"><span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-lg text-on-surface-variant">search</span><input v-model="query" class="w-full rounded-lg border border-white/10 bg-surface-container py-2.5 pl-10 pr-4 text-sm outline-none transition-colors placeholder:text-outline focus:border-primary/50" placeholder="搜索新闻标题、来源或内容"></label></div></header><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><div v-if="results.length" class="divide-y divide-white/10 border-b border-white/10"><article v-for="item in results" :key="item.id" class="group grid gap-5 py-6 sm:grid-cols-[210px_1fr]"><a v-if="item.image" :href="item.url||undefined" target="_blank" class="overflow-hidden rounded-lg bg-surface-container"><img :src="item.image" :alt="item.title" class="aspect-[16/10] h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" loading="lazy"></a><div :class="item.image?'':'sm:col-span-2'"><div class="flex flex-wrap items-center gap-3 text-xs"><span class="font-bold uppercase tracking-widest text-primary">{{item.category}}</span><time class="text-outline">{{formatDate(item.publishedAt)}}</time></div><h2 class="mt-2 text-xl font-extrabold leading-7 transition-colors group-hover:text-primary">{{item.title}}</h2><p class="mt-3 text-sm leading-6 text-on-surface-variant">{{item.summary}}</p><a v-if="item.url" :href="item.url" target="_blank" rel="noreferrer" class="mt-4 inline-flex items-center gap-1 text-sm font-bold text-primary">阅读原文<span class="material-symbols-outlined text-lg">open_in_new</span></a></div></article></div><div v-else class="rounded-xl border border-dashed border-white/10 py-16 text-center text-sm text-on-surface-variant">没有找到与“{{query}}”相关的新闻。</div></template></PageState></main><GlobalFooter/></div></template>
