<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchPopularPeople } from '../services/catalog-api'
const route=useRoute();const router=useRouter();const page=computed(()=>Number(route.query.page||1));const department=computed(()=>typeof route.query.department==='string'?route.query.department:'');const key=computed(()=>page.value+':'+department.value);const {data,loading,error,reload}=useAsyncData(()=>fetchPopularPeople(page.value),[key])
const people=computed(()=>department.value?data.value?.results.filter(person=>person.department===department.value)||[]:data.value?.results||[])
const title=computed(()=>department.value==='Acting'?'热门演员':department.value==='Directing'?'热门导演与编剧':'热门影人')
function setPage(value:number){router.push({query:{page:Math.max(1,Math.min(data.value?.totalPages||1,value))}})}
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto max-w-[1216px] px-4 pb-16 pt-[82px] md:px-8"><header class="mb-7 border-b border-white/10 pb-6"><p class="text-xs font-bold uppercase tracking-widest text-primary">人物资料</p><h1 class="mt-2 text-3xl font-extrabold md:text-4xl">{{title}}</h1><p class="mt-3 text-sm text-on-surface-variant">当前最受关注的演员、导演与影视工作者。</p></header><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><div v-if="people.length" class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5"><RouterLink v-for="person in people" :key="person.id" :to="{name:'person',params:{id:person.id}}" class="group rounded-xl border border-white/5 bg-surface-container p-3"><img :src="person.profile" :alt="person.name" class="aspect-[4/5] w-full rounded-lg object-cover"><h2 class="mt-3 truncate text-base font-bold group-hover:text-primary">{{person.name}}</h2><p class="mt-1 text-xs text-on-surface-variant">{{person.department||'影视工作者'}}</p><p class="mt-2 line-clamp-2 text-xs leading-5 text-on-surface-variant">{{person.knownFor.map(item=>item.title).join('、')||'暂无代表作品'}}</p></RouterLink></div><div v-else class="rounded-xl border border-dashed border-white/10 py-16 text-center text-sm text-on-surface-variant">本页暂无符合职业条件的热门影人，请查看下一页。</div><nav class="mt-10 flex items-center justify-center gap-2"><button class="rounded bg-surface-container px-4 py-2 disabled:opacity-40" :disabled="page<=1" @click="setPage(page-1)">上一页</button><span class="rounded bg-primary-container px-4 py-2 font-bold text-on-primary-container">{{page}}</span><button class="rounded bg-surface-container px-4 py-2 disabled:opacity-40" :disabled="page>=data.totalPages" @click="setPage(page+1)">下一页</button></nav></template></PageState></main><GlobalFooter/></div></template>
