<script setup lang="ts">
import { computed } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import PageState from '../components/catalog/PageState.vue'
import PaginationBar from '../components/catalog/PaginationBar.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchPopularPeople } from '../services/catalog-api'
const route=useRoute(),router=useRouter(),page=computed(()=>Number(route.query.page||1)),department=computed(()=>typeof route.query.department==='string'?route.query.department:''),key=computed(()=>page.value+':'+department.value)
const {data,loading,error,reload}=useAsyncData(()=>fetchPopularPeople(page.value,department.value||undefined),[key])
const title=computed(()=>department.value==='Acting'?'热门演员':department.value==='Creators'?'热门导演与编剧':'热门影人')
function setPage(value:number){router.push({query:{...route.query,page:value}});scrollTo({top:0,behavior:'smooth'})}
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto max-w-[1216px] px-4 pb-16 pt-[82px] md:px-8"><header class="mb-8 border-b border-white/10 pb-6"><p class="text-xs font-bold uppercase tracking-widest text-primary">影人发现</p><h1 class="mt-2 text-3xl font-extrabold md:text-4xl">{{title}}</h1><p class="mt-3 text-sm text-on-surface-variant">浏览当前受到关注的演员、导演、编剧与影视创作者。</p></header><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><div v-if="data.results.length" class="grid grid-cols-2 gap-5 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5"><RouterLink v-for="person in data.results" :key="person.id" :to="{name:'person',params:{id:person.id}}" class="person-card group"><div class="relative aspect-[4/5] overflow-hidden rounded-xl bg-surface-container-high"><img :src="person.profile" :alt="person.name" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent opacity-60 transition-opacity group-hover:opacity-90"></div><span class="absolute bottom-3 left-3 rounded bg-black/65 px-2 py-1 text-[10px] font-bold text-primary backdrop-blur">{{person.department||'影视工作者'}}</span></div><div class="p-3"><h2 class="truncate text-base font-bold transition-colors group-hover:text-primary">{{person.name}}</h2><p class="mt-2 line-clamp-2 min-h-10 text-xs leading-5 text-on-surface-variant">{{person.knownFor.map(item=>item.title).join('、')||'暂无代表作品'}}</p></div></RouterLink></div><div v-else class="rounded-xl border border-dashed border-white/10 py-16 text-center text-sm text-on-surface-variant">当前分类暂无可展示的热门影人。</div><PaginationBar :page="page" :total-pages="data.totalPages" :total-results="data.totalResults" label="位影人" @change="setPage"/></template></PageState></main><GlobalFooter/></div></template>
<style scoped>.person-card{overflow:hidden;border:1px solid rgba(255,255,255,.05);border-radius:14px;background:#1d2025;transition:all .3s ease}.person-card:hover{transform:translateY(-5px);border-color:rgba(245,197,24,.28);background:#23262c;box-shadow:0 18px 38px rgba(0,0,0,.3)}</style>
