<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import CatalogPosterCard from '../components/catalog/CatalogPosterCard.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchPerson } from '../services/catalog-api'
import { formatDate } from '../utils/format'
const route=useRoute();const id=computed(()=>String(route.params.id));const {data,loading,error,reload}=useAsyncData(()=>fetchPerson(id.value),[id])
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto max-w-[1216px] px-4 pb-16 pt-[82px] md:px-8"><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><section class="grid gap-8 md:grid-cols-[260px_1fr]"><div><img :src="data.profile" :alt="data.name" class="w-full rounded-xl border border-white/5 object-cover"><a v-if="data.imdbUrl" :href="data.imdbUrl" target="_blank" class="mt-4 flex items-center justify-center gap-2 rounded bg-surface-container py-3 text-sm font-bold hover:text-primary">IMDb 人物页<span class="material-symbols-outlined text-lg">open_in_new</span></a></div><div><p class="text-xs font-bold uppercase tracking-widest text-primary">{{data.department||'影视工作者'}}</p><h1 class="mt-2 text-4xl font-extrabold">{{data.name}}</h1><p v-if="data.alsoKnownAs.length" class="mt-2 text-sm text-on-surface-variant">又名：{{data.alsoKnownAs.slice(0,5).join('、')}}</p><dl class="mt-6 grid max-w-2xl gap-3 text-sm sm:grid-cols-2"><div class="rounded bg-surface-container p-3"><dt class="text-on-surface-variant">出生日期</dt><dd class="mt-1 font-bold">{{formatDate(data.birthday)}}</dd></div><div class="rounded bg-surface-container p-3"><dt class="text-on-surface-variant">出生地</dt><dd class="mt-1 font-bold">{{data.placeOfBirth||'暂无'}}</dd></div></dl><section class="mt-8"><h2 class="mb-4 text-2xl font-extrabold">人物简介</h2><p class="whitespace-pre-line text-[15px] leading-7 text-on-surface-variant">{{data.biography}}</p></section></div></section><section v-if="data.images.length>1" class="mt-12"><h2 class="mb-5 text-2xl font-extrabold">人物图片</h2><div class="flex gap-3 overflow-x-auto pb-2"><a v-for="picture in data.images" :key="picture" :href="picture" target="_blank" class="w-32 flex-none"><img :src="picture" class="aspect-[4/5] w-full rounded-lg object-cover"></a></div></section><section class="mt-12"><h2 class="mb-5 text-2xl font-extrabold">代表作品</h2><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6"><CatalogPosterCard v-for="item in data.credits" :key="item.mediaType+item.id" :item="item"/></div></section></template></PageState></main><GlobalFooter/></div></template>
