<script setup lang="ts">
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchWatchProviders } from '../services/catalog-api'
const {data,loading,error,reload}=useAsyncData(fetchWatchProviders)
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><main class="mx-auto max-w-[1216px] px-4 pb-16 pt-[82px] md:px-8"><header class="mb-7 border-b border-white/10 pb-6"><p class="text-xs font-bold uppercase tracking-widest text-primary">中国区观看服务</p><h1 class="mt-2 text-3xl font-extrabold md:text-4xl">观看平台</h1><p class="mt-3 text-sm text-on-surface-variant">选择 TMDB 已收录的观看平台，进入对应电影或剧集筛选。</p></header><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6"><article v-for="provider in data" :key="provider.id" class="rounded-xl border border-white/5 bg-surface-container p-4"><img :src="provider.logo" :alt="provider.name" class="mx-auto h-16 w-16 rounded-xl object-cover"><h2 class="mt-3 truncate text-center text-sm font-bold">{{provider.name}}</h2><div class="mt-3 flex justify-center gap-2"><RouterLink v-if="provider.media.includes('movie')" :to="{name:'explore',query:{media:'movie',provider:provider.id}}" class="rounded bg-surface-container-high px-3 py-1.5 text-xs font-bold hover:text-primary">电影</RouterLink><RouterLink v-if="provider.media.includes('tv')" :to="{name:'explore',query:{media:'tv',provider:provider.id}}" class="rounded bg-surface-container-high px-3 py-1.5 text-xs font-bold hover:text-primary">剧集</RouterLink></div></article></div></template></PageState></main><GlobalFooter/></div></template>
