
<script setup lang="ts">
import {computed} from 'vue'
import {useRoute} from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import PageState from '../components/catalog/PageState.vue'
import {useAsyncData} from '../composables/useAsyncData'
import {profileApi} from '../services/user-api'
const route=useRoute(),username=computed(()=>String(route.params.username)),key=computed(()=>username.value),{data,loading,error,reload}=useAsyncData(()=>profileApi.public(username.value),[key])
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><main class="pb-20 pt-[50px]"><section class="mx-auto mb-12 max-w-[1216px] px-4 pt-8 md:px-8"><div class="relative mb-[-55px] h-[260px] overflow-hidden rounded-xl group"><img :src="data.user.bannerUrl" class="h-full w-full object-cover opacity-60 transition-transform duration-700 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent"></div></div><div class="relative flex flex-col items-end gap-8 md:flex-row"><img :src="data.user.avatarUrl" class="h-36 w-36 rounded-xl border-4 border-background object-cover shadow-2xl"><div class="flex-1 pb-3"><h1 class="text-3xl font-extrabold">{{data.user.displayName}}</h1><p class="mt-2 text-sm text-outline">@{{data.user.username}}</p><p class="mt-3 max-w-2xl text-on-surface-variant">{{data.user.bio||'这位用户暂未填写个人简介。'}}</p></div></div></section><section class="mx-auto mb-12 grid max-w-[1216px] grid-cols-2 gap-4 px-4 md:grid-cols-4 md:px-8"><div v-for="item in [['看过',data.stats.watchedCount],['评分',data.stats.ratingCount],['短评',data.stats.reviewCount],['收藏',data.stats.favoriteCount]]" :key="item[0]" class="rounded-xl border border-white/5 bg-surface-container p-6 text-center"><strong class="block text-3xl text-primary">{{item[1]||0}}</strong><span class="mt-1 block text-xs text-on-surface-variant">{{item[0]}}</span></div></section><section class="mx-auto max-w-[1216px] px-4 md:px-8"><h2 class="mb-6 border-b border-white/10 pb-4 text-2xl font-bold">最近观影动态</h2><div v-if="data.entries.length" class="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6"><RouterLink v-for="entry in data.entries" :key="entry.id" :to="{name:'title',params:{type:entry.mediaType,id:entry.tmdbId}}" class="group"><div class="aspect-[2/3] overflow-hidden rounded-lg bg-surface-container"><img :src="entry.posterUrl||''" :alt="entry.title" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"></div><h3 class="mt-3 truncate font-bold group-hover:text-primary">{{entry.title}}</h3><p v-if="entry.rating" class="mt-1 text-sm font-bold text-primary">{{entry.rating.toFixed(1)}} / 10</p><p v-if="entry.reviewText" class="mt-2 line-clamp-3 text-xs leading-5 text-on-surface-variant">{{entry.containsSpoiler?'该短评含剧透':''}}{{entry.containsSpoiler?' · ':''}}{{entry.reviewText}}</p></RouterLink></div><div v-else class="rounded-xl border border-dashed border-white/10 py-16 text-center text-on-surface-variant">这位用户还没有公开记录。</div></section></main></template></PageState><GlobalFooter/></div></template>
