<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import CatalogPosterCard from '../components/catalog/CatalogPosterCard.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchTitle } from '../services/catalog-api'
import { formatCount, formatDate, formatMoney, formatRuntime } from '../utils/format'
const route=useRoute();const type=computed(()=>String(route.params.type));const id=computed(()=>String(route.params.id));const key=computed(()=>type.value+':'+id.value)
const {data,loading,error,reload}=useAsyncData(()=>fetchTitle(type.value,id.value),[key])
const expanded=ref(false);const moreImages=ref(false);const moreDetails=ref(false);const copied=ref(false);const userRating=ref(0);const watchState=ref('')
const cast=computed(()=>data.value?.credits.cast.slice(0,expanded.value?18:8)||[]);const images=computed(()=>data.value?.images.slice(0,moreImages.value?12:6)||[]);const trailer=computed(()=>data.value?.videos.find(v=>v.type==='Trailer'&&v.official)||data.value?.videos[0])
function setWatch(value:string){watchState.value=watchState.value===value?'':value;localStorage.setItem('moviescope:watch:'+key.value,watchState.value)}
function rate(value:number){userRating.value=value;localStorage.setItem('moviescope:rating:'+key.value,String(value))}
async function share(){
  const value=data.value?.imdbUrl||location.href
  try { await navigator.clipboard.writeText(value) } catch {
    const input=document.createElement('textarea');input.value=value;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()
  }
  copied.value=true;setTimeout(()=>copied.value=false,1500)
}
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><main class="pb-16 pt-[50px]">
<section class="relative overflow-hidden border-b border-white/5"><img :src="data.backdrop||data.poster" class="absolute inset-0 h-full w-full object-cover opacity-35"><div class="absolute inset-0 bg-gradient-to-r from-background via-background/90 to-background/40"></div><div class="absolute inset-0 bg-gradient-to-t from-background via-transparent to-black/30"></div><div class="relative mx-auto grid max-w-[1216px] gap-7 px-4 py-12 md:grid-cols-[240px_1fr] md:px-8 md:py-16"><img :src="data.poster" :alt="data.title" class="w-48 rounded-xl border border-white/10 shadow-2xl md:w-full"><div class="self-end"><div class="mb-3 flex flex-wrap gap-2"><RouterLink v-for="genre in data.genres" :key="genre" :to="{name:'search',query:{q:genre,type:data.mediaType}}" class="rounded border border-primary/35 bg-black/35 px-2.5 py-1 text-[10px] font-bold text-primary">{{genre}}</RouterLink></div><h1 class="text-3xl font-extrabold md:text-5xl">{{data.title}}</h1><p v-if="data.originalTitle&&data.originalTitle!==data.title" class="mt-2 text-sm text-on-surface-variant">{{data.originalTitle}}</p><p v-if="data.tagline" class="mt-4 text-lg italic text-on-surface-variant">“{{data.tagline}}”</p><div class="mt-4 flex flex-wrap gap-3 text-sm text-on-surface-variant"><span>{{data.year}}</span><span>{{data.certification||'未分级'}}</span><span>{{formatRuntime(data.runtime)}}</span><span>{{data.mediaType==='tv'?'剧集':'电影'}}</span></div><div class="mt-6 flex flex-wrap gap-3"><button class="detail-action bg-primary-container text-on-primary-container" @click="setWatch('want')"><span class="material-symbols-outlined">add</span>{{watchState==='want'?'已想看':'想看'}}</button><a v-if="trailer" :href="trailer.url" target="_blank" class="detail-action border border-white/15 bg-black/25"><span class="material-symbols-outlined">play_arrow</span>播放预告片</a><button class="detail-action border border-white/15 bg-black/25" @click="setWatch('watched')"><span class="material-symbols-outlined">visibility</span>{{watchState==='watched'?'已看过':'看过'}}</button></div></div></div></section>
<div class="mx-auto grid max-w-[1216px] gap-8 px-4 py-10 md:px-8 lg:grid-cols-[minmax(0,1fr)_300px]"><div class="min-w-0 space-y-12">
<section><h2 class="section-title">剧情简介</h2><p class="text-[15px] leading-7 text-on-surface-variant">{{data.overview}}</p><div class="mt-5 flex flex-wrap gap-2"><RouterLink v-for="keyword in data.keywords.slice(0,12)" :key="keyword.id" :to="{name:'search',query:{q:keyword.name,type:'keyword'}}" class="rounded-full bg-surface-container px-3 py-1 text-xs text-on-surface-variant hover:text-primary"># {{keyword.name}}</RouterLink></div></section>
<section><div class="mb-5 flex justify-between"><h2 class="section-title mb-0">演职员表</h2><button class="text-sm font-bold text-primary" @click="expanded=!expanded">{{expanded?'收起':'查看全部'}}</button></div><div class="grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8"><RouterLink v-for="person in cast" :key="person.id" :to="{name:'person',params:{id:person.id}}"><img :src="person.profile" class="aspect-[4/5] w-full rounded-lg object-cover"><h3 class="mt-2 truncate text-sm font-bold hover:text-primary">{{person.name}}</h3><p class="truncate text-xs text-on-surface-variant">{{person.character}}</p></RouterLink></div><div class="mt-5 flex flex-wrap gap-2"><RouterLink v-for="person in data.credits.crew" :key="person.id+(person.job||'')" :to="{name:'person',params:{id:person.id}}" class="rounded bg-surface-container px-3 py-2 text-xs text-on-surface-variant hover:text-primary">{{person.job}} · {{person.name}}</RouterLink></div></section>
<section v-if="data.images.length"><div class="mb-5 flex justify-between"><h2 class="section-title mb-0">剧照与图片</h2><button class="text-sm font-bold text-primary" @click="moreImages=!moreImages">{{moreImages?'收起':'查看全部'}}</button></div><div class="grid grid-cols-2 gap-3 md:grid-cols-3"><a v-for="picture in images" :key="picture.path" :href="picture.path" target="_blank"><img :src="picture.path" class="aspect-video w-full rounded-lg object-cover"></a></div></section>
<section><h2 class="section-title">精彩影评</h2><div v-if="data.reviews.length" class="space-y-3"><article v-for="review in data.reviews" :key="review.id" class="rounded-xl border border-white/5 bg-surface-container p-5"><div class="flex justify-between"><b>{{review.author}}</b><span v-if="review.rating" class="font-black text-primary">{{review.rating}} / 10</span></div><p class="mt-3 line-clamp-5 whitespace-pre-line text-sm leading-6 text-on-surface-variant">{{review.content}}</p><time class="mt-3 block text-xs text-outline">{{formatDate(review.createdAt)}}</time></article></div><div v-else class="rounded-xl border border-dashed border-white/10 py-12 text-center text-sm text-on-surface-variant">当前暂无公开影评</div></section>
<section><h2 class="section-title">相似{{data.mediaType==='tv'?'剧集':'电影'}}推荐</h2><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6"><CatalogPosterCard v-for="item in (data.similar.length?data.similar:data.recommendations).slice(0,6)" :key="item.id" :item="item"/></div></section></div>
<aside class="space-y-6 lg:sticky lg:top-[66px] lg:h-fit"><section class="detail-panel"><h3 class="panel-title">媒体口碑</h3><a v-if="data.imdbUrl" :href="data.imdbUrl" target="_blank" class="rating-row"><div><b class="text-primary">IMDb</b><p class="text-2xl font-black">{{data.imdbRating?.toFixed(1)||'暂无'}} <small>/10</small></p><span>{{formatCount(data.imdbVoteCount)}} 人评分</span></div><span class="material-symbols-outlined text-primary">open_in_new</span></a><a :href="'https://www.themoviedb.org/'+data.mediaType+'/'+data.id" target="_blank" class="rating-row"><div><b class="text-primary">TMDB</b><p class="text-2xl font-black">{{data.tmdbRating?.toFixed(1)||'暂无'}} <small>/10</small></p><span>{{formatCount(data.tmdbVoteCount)}} 人评分</span></div><span class="material-symbols-outlined text-primary">open_in_new</span></a></section>
<section class="detail-panel"><h3 class="panel-title">你的互动</h3><p class="mt-4 text-sm text-on-surface-variant">为这部作品评分</p><div class="mt-2 flex flex-wrap"><button v-for="star in 10" :key="star" class="material-symbols-outlined text-xl" :class="star<=userRating?'text-primary':'text-outline'" @click="rate(star)">star</button></div><button class="mt-4 flex w-full items-center justify-center gap-2 rounded bg-surface-container-high py-3 text-sm font-bold" @click="share"><span class="material-symbols-outlined">share</span>{{copied?'已复制 IMDb 链接':'分享电影'}}</button></section>
<section class="detail-panel"><h3 class="panel-title">{{data.mediaType==='tv'?'剧集':'电影'}}详情</h3><dl class="mt-4 space-y-3 text-sm"><div class="detail-pair"><dt>上映日期</dt><dd>{{formatDate(data.releaseDate)}}</dd></div><div class="detail-pair"><dt>状态</dt><dd>{{data.status||'暂无'}}</dd></div><div class="detail-pair"><dt>制作公司</dt><dd>{{data.productionCompanies.slice(0,2).map(c=>c.name).join('、')||'暂无'}}</dd></div><template v-if="moreDetails"><div class="detail-pair"><dt>预算</dt><dd>{{formatMoney(data.budget)}}</dd></div><div class="detail-pair"><dt>票房</dt><dd>{{formatMoney(data.revenue)}}</dd></div><div class="detail-pair"><dt>语言</dt><dd>{{data.languages.join('、')||'暂无'}}</dd></div></template></dl><button class="mt-4 w-full rounded bg-surface-container-high py-3 text-sm font-bold text-on-surface-variant" @click="moreDetails=!moreDetails">{{moreDetails?'收起信息':'显示更多信息'}}</button></section>
<section v-if="data.watchProviders?.flatrate?.length" class="detail-panel"><h3 class="panel-title">观看平台</h3><a :href="data.watchProviders.link" target="_blank" class="mt-4 flex flex-wrap gap-2"><img v-for="provider in data.watchProviders.flatrate" :key="provider.provider_id" :src="'https://image.tmdb.org/t/p/w92'+provider.logo_path" :alt="provider.provider_name" class="h-10 w-10 rounded-lg"></a></section><div class="flex gap-3"><a v-if="data.homepage" :href="data.homepage" target="_blank" class="side-action">官方网站</a><button class="side-action" @click="share">{{copied?'已复制':'分享'}}</button></div></aside></div></main></template></PageState><GlobalFooter/></div></template>
<style scoped>.detail-action{display:inline-flex;height:40px;align-items:center;gap:8px;border-radius:4px;padding:0 16px;font-weight:700}.section-title{margin-bottom:20px;font-size:24px;font-weight:800}.detail-panel{border:1px solid rgba(255,255,255,.05);border-radius:12px;background:#1d2025;padding:20px}.panel-title{border-bottom:1px solid rgba(255,255,255,.1);padding-bottom:12px;font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#c5c7ce}.rating-row{margin-top:12px;display:flex;align-items:center;justify-content:space-between;border-radius:8px;background:#282a30;padding:16px}.rating-row span{font-size:12px;color:#c5c7ce}.detail-pair{display:flex;justify-content:space-between;gap:16px}.detail-pair dt{color:#c5c7ce}.detail-pair dd{text-align:right}.side-action{flex:1;border:1px solid rgba(255,255,255,.05);border-radius:12px;background:#1d2025;padding:12px;text-align:center;font-size:12px;font-weight:700}</style>
