<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import GlobalHeader from '../components/global/GlobalHeader.vue'
import GlobalFooter from '../components/global/GlobalFooter.vue'
import PageState from '../components/catalog/PageState.vue'
import { useAsyncData } from '../composables/useAsyncData'
import { fetchTitle } from '../services/catalog-api'
const route=useRoute(), type=computed(()=>String(route.params.type)), id=computed(()=>String(route.params.id)), key=computed(()=>type.value+':'+id.value)
const {data,loading,error,reload}=useAsyncData(()=>fetchTitle(type.value,id.value),[key])
const departments=computed(()=>{const map=new Map<string,NonNullable<typeof data.value>['credits']['crew']>();for(const person of data.value?.credits.crew||[]){const name=person.department||'其他';if(!map.has(name))map.set(name,[]);map.get(name)?.push(person)}return [...map.entries()]})
</script>
<template><div class="min-h-screen bg-background text-on-surface"><GlobalHeader/><PageState :loading="loading" :error="error" @retry="reload"><template v-if="data"><main class="mx-auto max-w-[1216px] px-4 pb-24 pt-24 md:px-8"><RouterLink :to="{name:'title',params:{type:data.mediaType,id:data.id}}" class="text-sm font-bold text-primary">← 返回详情</RouterLink><div class="mt-7 flex items-end gap-5"><img :src="data.poster" class="h-32 w-24 rounded-lg object-cover"/><div><p class="text-sm text-on-surface-variant">{{ data.originalTitle }}</p><h1 class="mt-1 text-4xl font-black">{{ data.title }} · 完整演职员表</h1><p class="mt-3 text-sm text-on-surface-variant">演员 {{ data.credits.cast.length }} 位 · 工作人员 {{ data.credits.crew.length }} 位</p></div></div><section class="mt-12"><h2 class="section-heading">演员与角色</h2><div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><RouterLink v-for="person in data.credits.cast" :key="person.id+':'+person.character" :to="{name:'person',params:{id:person.id}}" class="credit-card"><img :src="person.profile" :alt="person.name"/><div class="min-w-0"><h3>{{ person.name }}</h3><p>{{ person.character || '角色信息暂无' }}</p><span>演员</span></div></RouterLink></div></section><section v-for="[department,people] in departments" :key="department" class="mt-12"><h2 class="section-heading">{{ department }}</h2><div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><RouterLink v-for="person in people" :key="person.id+':'+person.job" :to="{name:'person',params:{id:person.id}}" class="credit-card"><img :src="person.profile" :alt="person.name"/><div class="min-w-0"><h3>{{ person.name }}</h3><p>{{ person.job || department }}</p><span>{{ department }}</span></div></RouterLink></div></section></main></template></PageState><GlobalFooter/></div></template>
<style scoped>.section-heading{font-size:24px;font-weight:800;border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:14px}.credit-card{display:flex;gap:14px;align-items:center;border:1px solid rgba(255,255,255,.06);border-radius:14px;background:rgba(255,255,255,.025);padding:12px;transition:.2s}.credit-card:hover{border-color:rgba(245,197,24,.35);transform:translateY(-2px)}.credit-card img{width:72px;height:90px;flex:none;border-radius:10px;object-fit:cover}.credit-card h3{font-weight:800}.credit-card p{margin-top:4px;color:rgba(255,255,255,.65);font-size:13px}.credit-card span{display:inline-block;margin-top:7px;color:#f5c518;font-size:10px;text-transform:uppercase;letter-spacing:.08em}</style>
